name: Release binary artifacts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            image: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            image: windows-latest
          - target: x86_64-apple-darwin
            image: macos-latest

    steps:
      - name: Download artifacts
        run: curl https://github.com/babymotte/worterbuch/releases/download/${{ github.ref_name }}/worterbuch-${{ matrix.target }}.zip -o worterbuch-${{ matrix.target }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: worterbuch-${{ matrix.target }}.zip

  docker:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull
        shell: bash
        run: VERSION="${{ github.ref_name }}" && docker pull babymotte/worterbuch:${VERSION/"v"/""}

      - name: Docker tag
        shell: bash
        run: VERSION="${{ github.ref_name }}" && docker tag babymotte/worterbuch:${VERSION/"v"/""} wb-pro/worterbuch:${VERSION/"v"/""}

      - name: Docker push
        shell: bash
        run: VERSION="${{ github.ref_name }}" && docker push wb-pro/worterbuch:${VERSION/"v"/""}
